# Generated by Django 4.2.6 on 2023-10-25 06:12

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor): 
    call_command('loaddata', 'books/fixtures/books.json')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('authentication', '0002_load_fixtures'), 
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]