# Generated by Django 4.2.4 on 2023-10-28 06:52
# Generated by Django 4.2.6 on 2023-10-30 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interest_subjects', models.ManyToManyField(blank=True, default=None, related_name='interested_members', to='authentication.subject')),
                ('match_received', models.ManyToManyField(blank=True, related_name='received_matches', to='authentication.member')),
                ('match_sent', models.ManyToManyField(blank=True, related_name='sent_matches', to='authentication.member')),
            ],
        ),
    ]
