# Generated by Django 4.2.6 on 2023-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20231023_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subjects',
        ),
        migrations.AddField(
            model_name='member',
            name='interest_subjects',
            field=models.ManyToManyField(related_name='interested_members', to='authentication.subject'),
        ),
    ]
