# Generated by Django 4.2.6 on 2023-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='match_received',
            field=models.ManyToManyField(blank=True, default=None, to='authentication.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='match_sent',
            field=models.ManyToManyField(blank=True, default=None, to='authentication.member'),
        ),
    ]
