# Generated by Django 4.2.6 on 2023-10-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_member_account_remove_member_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='interest_subjects',
            field=models.ManyToManyField(blank=True, default=None, related_name='interested_members', to='authentication.subject'),
        ),
    ]
