# Generated by Django 4.2.6 on 2023-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_member_match_received_alter_member_match_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='match_received',
            field=models.ManyToManyField(blank=True, related_name='received_matches', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='match_sent',
            field=models.ManyToManyField(blank=True, related_name='sent_matches', to='authentication.member'),
        ),
    ]
