# Generated by Django 4.2.6 on 2023-10-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_member_match_received_member_match_sent'),
        ('book_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
                ('subjects', models.ManyToManyField(to='authentication.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
