# Generated by Django 5.0 on 2023-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_member_match_received_alter_member_match_sent'),
        ('book_request', '0002_alter_bookrequest_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='subjects',
            field=models.ManyToManyField(to='authentication.subject'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
