# Generated by Django 4.2.6 on 2023-10-29 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0003_alter_bookrequest_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='date_requested',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
