# Generated by Django 5.0 on 2023-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0004_alter_bookrequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
